name: Docker build and push
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  jemalloc:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        ruby: ["3.1"]
        version: ["default", "jemalloc", "nodejs", "nodejs-jemalloc"]

    env:
      DOCKER_BUILDKIT: 1
      DOCKER_IMAGE: acornsaustralia/ruby
      POSTGRES_VERSION: 16
      ROCKY_VERSION: 9
      RUBY_VERSION: ${{ matrix.ruby }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

      - name: Build image
        run: docker compose build ${{ matrix.version }}

      - name: Tag image
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker tag ruby:${{ matrix.ruby }}-${{ matrix.version }} ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}
          docker tag ruby:${{ matrix.ruby }}-${{ matrix.version }} ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}-${{ github.run_number }}

      - name: Log into registry
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://index.docker.io/v1/ -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push images
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}-${{ github.run_number }}
