# TODO Remove after ruby 3 migration

name: Docker build and push
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * 0"

env:
  DOCKER_BUILDKIT: 1
  DOCKER_IMAGE: "acornsaustralia/ruby"
  ROCKY_VERSION: 8
  POSTGRES_VERSION: 14

jobs:
  r8-ruby:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        ruby: ["2.7"]
        version: [
          "r8-nodejs",
          "r8-nodejs-jemalloc"
        ]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: r8.Dockerfile
          config: hadolint-ci.yaml

      - name: Render docker-compose.yml
        run: RUBY_VERSION=${{ matrix.ruby }} envsubst <  docker-compose.yml.tmpl >  docker-compose.yml

      - name: Build image
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml build ${{ matrix.version }}

      - name: Tag image
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker tag ruby:${{ matrix.ruby }}-${{ matrix.version }} ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}
          docker tag ruby:${{ matrix.ruby }}-${{ matrix.version }} ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}-${{ github.run_number }}

      - name: Log into registry
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://index.docker.io/v1/ -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push images
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ matrix.version }}-${{ github.run_number }}
