name: Docker build and push
on:   
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 0"

env:
  IMAGE_NAME: ruby

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        ruby: [
          '3.0'
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

      - name: Render docker-compose.yml
        run: RUBY_VERSION=${{ matrix.ruby }} FEDORA_VERSION=35 envsubst <  docker-compose.yml.tmpl >  docker-compose.yml

      - name: Build image
        run: docker-compose -f docker-compose.yml build ruby

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://index.docker.io/v1/ -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: docker-compose -f docker-compose.yml push ruby

      - name: Tag build-versioned image
        run: docker tag acornsaustralia/ruby:${{ matrix.ruby }} acornsaustralia/ruby:${{ matrix.ruby }}-${{ github.run_number }}

      - name: Push versioned image
        run: docker push acornsaustralia/ruby:${{ matrix.ruby }}-${{ github.run_number }}
